PLUGIN_VERSION = "40.20.4"
RELEASE_LABEL = "ALPHA-40.20.4"
PUBLIC_EXPERIMENTAL_LIMITED = True
PREVIEW_JOBS_GUARD_ENABLED = False  # ALPHA-40.20.4: lightweight FOV renderer runs with normal QGIS preview jobs.
